### ISSUE TITLE
Looks like our libraries are very similar :)

### ISSUE THREAD

**Issue by fitzgen** [philipc/rust-dwarf#1]
Makes sense since they are both DWARF parsers :)

https://github.com/fitzgen/gimli

Maybe worth sharing a LEB128 implementation? I already published mine as a separate crate: https://github.com/fitzgen/leb128

Cheers!

Nick

**Comment by philipc** [comment]
Thanks for letting me know.  I'll check it out in a few days.

**Comment by philipc** [comment]
I'm happy to share the LEB128 implementation. There's still a benchmark difference that I want to track down before switching over.

It's interesting to see the differences in our libraries. Still very similar though. But you write excellent documentation :)

Do you see any useful differences between the libraries? Is it worth merging them too?  A couple of differences that may not be able to be merged are:

- using Cow to allow write support
- using endian parameters instead of traits, to allow easy runtime selection of endianness

**Comment by fitzgen** [comment]
I suggested starting with sharing a LEB128 implementation because I felt it would be easiest. I'm very interested in the benchmarking you mention because LEB128 parsing is very core to the library and its performance has implications about the whole library's performance.

> Do you see any useful differences between the libraries?

A few things:

* I'm not interested in writing DWARF, just consuming it. That is, obviously, reflected in `gimli`. I'm not philosophically against having support for it in the library or anything, but I just have zero plans of doing that so I'm focused on my own use cases. It seems like your library has some support for programmatically constructing units and DIEs and writing them out.

* I don't want to deal with parsing object files -- there already exist libraries for parsing them and I think it is a separate concern in general. I might end up needing to write my on mach-o parser since I can't find any that look super reliable, but either way I still think it should be a separate crate.

* Regarding endianness, I think the vast majority of time users will be using little endian, and even when they are using big endian, it will be extremely rare that they are using both big and little endian dynamically. Therefore, I don't think it's worth having runtime cost (space and branches) to support this kind of thing. Perhaps ergonomics favors the runtime approach? I suppose the compile-time generic approach causes a certain amount of code bloat if the library user ends up instantiating both big and little endian specializations.

* `gimli` doesn't heap allocate a DIE's attributes by putting them in a `Vec`, it just provide an iterator (`AttrsIter`) that lazily parses them as necessary. In general I try to apply this principle to everything (except abbreviations). If the user wants to persist something in the heap, they can do it themselves; I don't want to impose that kind of cost when it isn't needed.

* I want to use strong typing for all the various kinds of offsets (into this unit, into this section, into other sections, etc...) because they are tricky to keep straight in practice. This is half-implemented right now.

A few things where it seems we have very similar goals:

* It seems we both intend to do mostly zero-copy parsing and have references to the original input buffer.

* It seems we both intend to parse units and DIEs lazily, although I think `gimli` goes a little further on this front (see note about `AttrsIter`).

    * We both use a cursor based approach for traversing the DIE tree. I don't really understand your cursor's `next_sibling` implementation. It seems that if one has a good `DW_AT_sibling`, then one should be able to just jump the iterator to the next sibling's offset in the current unit, and if not, then keep parsing in DFS order until the next sibling is reached. I don't see that reflected in your cursor's `next_sibling` but it seems like it is doing *something* but I just don't see it. FWIW, I haven't dug in too deep. I see that you are generic over any `Read` where I require the `&[u8]` bufffer. I like being generic in principle, but I wonder if it makes it harder to skip forward when searching for a next sibling. Perhaps requiring `Seek` would solve this tension?

> Is it worth merging them too?

Perhaps! I'm definitely open to the idea :)

As mentioned above, I thought it would be pretty easy to share a LEB128 crate, so I suggested that first.

Do you plan on supporting unwind information, location descriptions, and DWARF expressions in general? That is on my TODO list.

How do you plan on handling different types of units? Compilation units, type units, and partial units, oh my! I was thinking of having a `UnitHeader` trait or something... Haven't fleshed it out fully yet.

**Comment by fitzgen** [comment]
> I'm very interested in the benchmarking you mention because LEB128 parsing is very core to the library and its performance has implications about the whole library's performance.

FYI, I just pushed some basic `#[bench]` tests to the `leb128` crate. Hopefully they can serve as a baseline for discussions about LEB128 parsing performance.

**Comment by philipc** [comment]
>     I'm not interested in writing DWARF, just consuming it. That is, obviously, reflected in gimli. I'm not philosophically against having support for it in the library or anything, but I just have zero plans of doing that so I'm focused on my own use cases. It seems like your library has some support for programmatically constructing units and DIEs and writing them out.

My long term goal is to write tools for analyzing quality and performance of rust binaries, along the lines of https://github.com/acmel/dwarves. I have a few ideas for possible tools, but not sure yet if they are going to be feasible. At the same time, I figured it would be worth making a rust replacement for https://www.prevanders.net/dwarf.html because history has shown it's hard to write this safely.

>     I don't want to deal with parsing object files -- there already exist libraries for parsing them and I think it is a separate concern in general. I might end up needing to write my on mach-o parser since I can't find any that look super reliable, but either way I still think it should be a separate crate.

Not sure that I have an opinion on this yet. I don't like splitting things into external crates if the dependencies are too tight; it causes needless busy work when things need to change. It's much simpler if you can update both sides of the dependency at once. Parsing object files probably won't fall in that category though.

>     Regarding endianness, I think the vast majority of time users will be using little endian, and even when they are using big endian, it will be extremely rare that they are using both big and little endian dynamically. Therefore, I don't think it's worth having runtime cost (space and branches) to support this kind of thing. Perhaps ergonomics favors the runtime approach? I suppose the compile-time generic approach causes a certain amount of code bloat if the library user ends up instantiating both big and little endian specializations.

I pushed a commit to allow the user to choose between compile time and runtime. It turned out cleaner than I had expected.  But, annoyingly, it made things slower, even when changing to compile time :(  Another thing to track down...  This is the kind of problem that I want to develop tools to solve.

>     gimli doesn't heap allocate a DIE's attributes by putting them in a Vec, it just provide an iterator (AttrsIter) that lazily parses them as necessary. In general I try to apply this principle to everything (except abbreviations). If the user wants to persist something in the heap, they can do it themselves; I don't want to impose that kind of cost when it isn't needed.

I agree with the motivation, but I would want to measure the cost, instead of assuming it is cheaper.

>     I want to use strong typing for all the various kinds of offsets (into this unit, into this section, into other sections, etc...) because they are tricky to keep straight in practice. This is half-implemented right now.

Yeah I like that, and want to do it too once I have a better idea of what's needed.

>     It seems we both intend to do mostly zero-copy parsing and have references to the original input buffer.
> 
>     It seems we both intend to parse units and DIEs lazily, although I think gimli goes a little further on this front (see note about AttrsIter).

For these, my goal is to provide the best method possible, where best is defined in terms of speed and simplicity.  This is mostly based on gut feeling so far.

>         We both use a cursor based approach for traversing the DIE tree. I don't really understand your cursor's next_sibling implementation. It seems that if one has a good DW_AT_sibling, then one should be able to just jump the iterator to the next sibling's offset in the current unit, and if not, then keep parsing in DFS order until the next sibling is reached. I don't see that reflected in your cursor's next_sibling but it seems like it is doing something but I just don't see it. FWIW, I haven't dug in too deep. I see that you are generic over any Read where I require the &[u8] bufffer. I like being generic in principle, but I wonder if it makes it harder to skip forward when searching for a next sibling. Perhaps requiring Seek would solve this tension?

I haven't implemented DW_AT_sibling support yet, but you're right that it would let you jump the iterator. My current iterator keeps reading entries until it gets back to one at the same level. I use recursion to keep track of the level, returning when a null entry is reached. It's probably better to change that to a loop.

I'm using Read only where I don't need &[u8], which is mostly just for reading abbreviations. Not sure if it provides any real benefits though. All the entry reading still needs &[u8] for zero-copy returns.

> Do you plan on supporting unwind information, location descriptions, and DWARF expressions in general? That is on my TODO list.

Eventually, support everything. How soon, I don't know.

> How do you plan on handling different types of units? Compilation units, type units, and partial units, oh my! I was thinking of having a UnitHeader trait or something... Haven't fleshed it out fully yet.

I'm new to dwarf, so I don't know for sure, but I was hoping to have a `struct Unit` that could be used for all of them, and my `DieCursor` would only depend on `Unit`.

**Comment by fitzgen** [comment]
> My long term goal is to write tools for analyzing quality and performance of rust binaries, along the lines of https://github.com/acmel/dwarves. I have a few ideas for possible tools, but not sure yet if they are going to be feasible. At the same time, I figured it would be worth making a rust replacement for https://www.prevanders.net/dwarf.html because history has shown it's hard to write this safely.

Sounds about the same as my goals :) I want to eventually write a cross platform sampling profiler in Rust. Maybe also a simple stepping debugger. Many ideas, less time, so starting small and seeing how far I actually go :)

> I agree with the motivation, but I would want to measure the cost, instead of assuming it is cheaper.

Totally reasonable. Have to start with an initial implementation before you can get to comparing with an alternative :)

> I'm new to dwarf, so I don't know for sure, but I was hoping to have a struct Unit that could be used for all of them, and my DieCursor would only depend on Unit.

The reason I was leaning towards a `UnitHeader` trait is that the sizes of the headers are different, and so the offset in the unit where entries begin is different across different unit types. This makes composition a little bit trickier.

--------------------------------

So I'm getting to the point where I think we should collaborate/merge crates because it seems all of our goals are overlapping and we've just made some different (small) choices around implementation.

What do you think? If you're so inclined, we could start figuring out all the practicalities involved therein.

Also, would you like to be a collaborator for `leb128`?

We could make a github organization as an umbrella for this stuff too, but maybe I'm getting ahead of myself...

**Comment by fitzgen** [comment]
> I haven't implemented DW_AT_sibling support yet, but you're right that it would let you jump the iterator.

Heads up: I just implemented this in https://github.com/fitzgen/gimli/commit/4f723c2aa36e1689419c5a4f2d692a30e5b9b710

**Comment by philipc** [comment]
> The reason I was leaning towards a UnitHeader trait is that the sizes of the headers are different, and so the offset in the unit where entries begin is different across different unit types. This makes composition a little bit trickier.

I implemented what I meant in 2f15f3ee. The UnitCommon points past the header, so it doesn't care about the length.

> So I'm getting to the point where I think we should collaborate/merge crates because it seems all of our goals are overlapping and we've just made some different (small) choices around implementation.
> 
> What do you think? If you're so inclined, we could start figuring out all the practicalities involved therein.

Yes, I don't see any reason why a single library can't work for us both, so better not to duplicate effort. I'm happy to use either library as the starting point. I think my implementation is a little further along, but I'm lacking things such as docs, so it might make sense to start with gimli, and add stuff from rust-dwarf, updating docs as we go.

> Also, would you like to be a collaborator for leb128?

Sure, although I hope it's close to done now.

> We could make a github organization as an umbrella for this stuff too, but maybe I'm getting ahead of myself...

Whatever makes things easiest. Not sure an organization gains much at this point.

**Comment by philipc** [comment]
FYI: Implemented DW_AT_sibling in 6a56d4e. It uses the fact that it can only go forward, so again the header length doesn't matter.

**Comment by fitzgen** [comment]
> Yes, I don't see any reason why a single library can't work for us both, so better not to duplicate effort. I'm happy to use either library as the starting point. I think my implementation is a little further along, but I'm lacking things such as docs, so it might make sense to start with gimli, and add stuff from rust-dwarf, updating docs as we go.

I just pulled in your `src/constants.rs` file because I think your approach of open ended newtypes is better than my closed enum approach. Works much better in the face of future compatibility and extensions.

I would prefer to continue pulling pieces of rust-dwarf into gimli rather than the other way around, if that is alright with you. I think gimli has a bit more docs and unit tests, but is lacking in integration tests and examples in comparison to rust-dwarf. I've just added some raw section files (unpacked from their object file so as to be object file format independent) and an initial sanity test that gimli can parse all of the `.debug_abbrev` and `.debug_info` contents without parse errors.

Getting something like `UnitCommon` is a pretty high priority now, I think.

Also, porting adding some benches / porting rust-dwarf's benches would be nice.

Does this sound good? Are you ok with pulling rust-dwarf stuff into gimli?

Assuming yes, then I will add you as a collaborator. Should we move the repo to a github organization? Would you like to start reviewing each other's pull requests or just land commits directly until things get filled out and settle a bit more? (I definitely think that once a certain level of maturity is reached, everything should go through pull requests, and maybe we should even set up a homu/bors bot...)

Cheers!

**Comment by philipc** [comment]
That all sounds good to me. Using newtypes was going to be my first suggestion :) rust-dwarf's benches aren't very good, but I do think adding benches is important.

Your call on whether to use a github organization, I don't mind either way. I would like to use issues for the TODO list. At this stage, use pull requests for commits that you think need review, but land directly if you want. I wouldn't mind using pull requests for everything, just so there's somewhere to discuss it, even if you then merge without waiting for review. Simple fixes, and stuff like readme and version updates can be done directly still.

**Comment by fitzgen** [comment]
Great! Adding you as a collaborator now, then will start filing issues for the TODOs...

I also added some simple benches last night.

> At this stage, use pull requests for commits that you think need review, but land directly if you want. I wouldn't mind using pull requests for everything, just so there's somewhere to discuss it, even if you then merge without waiting for review. Simple fixes, and stuff like readme and version updates can be done directly still.

Ok, sounds good!

Going to go ahead and close this issue :)
